// <auto-generated />
using CarTrader.Services.Workflow.Infrastructure.Extensions.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarTrader.Services.Workflow.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240314193458_AddedBussinesKey")]
    partial class AddedBussinesKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarTrader.Services.Workflow.Domain.Models.CarProcess", b =>
                {
                    b.Property<string>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("BussinesKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CamundaProcessId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CarId");

                    b.ToTable("CarProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
