version: '3.3'
services:
  keycloak:
      image: quay.io/keycloak/keycloak:22.0.1
      container_name: keycloak
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        DB_VENDOR: h2
      command: start-dev
      volumes:
        - ./keycloak-db:/opt/keycloak/data/h2
      ports:
        - 8090:8080

  camunda:
      image: camunda/camunda-bpm-platform:tomcat-7.18.0
      container_name: camunda
      ports:
        - 8091:8080
      volumes:
        - ./camunda-data/camunda-h2-dbs:/camunda/camunda-h2-dbs
        - ./camunda-data/webapps/engine-rest/WEB-INF/web.xml:/camunda/webapps/engine-rest/WEB-INF/web.xml
  
  mssql:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: mssql
      environment:
        - MSSQL_SA_PASSWORD=Pass.123!
        - ACCEPT_EULA=Y
      ports:
        - 1433:1433
      volumes:
        - ./sqlserver/data:/var/opt/mssql/data

  rabbitmq:
      image: rabbitmq:3.9-management-alpine
      container_name: rabbitmq
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/mnesia

