// <auto-generated />
using CarTrader.Services.Diagnostic.Infrastructure.Extensions.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarTrader.Services.Diagnostic.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarTrader.Services.Diagnostic.Domain.Models.CarDiagnostic", b =>
                {
                    b.Property<string>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("AccidentSignsCheck")
                        .HasColumnType("bit");

                    b.Property<string>("AccidentSignsCheckRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BreakCheck")
                        .HasColumnType("bit");

                    b.Property<string>("BreakCheckRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BussinesKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CritcalErrorsCheck")
                        .HasColumnType("bit");

                    b.Property<string>("CritcalErrorsCheckRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnginePerformanceCheck")
                        .HasColumnType("bit");

                    b.Property<string>("EnginePerformanceCheckRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HistoryCheck")
                        .HasColumnType("bit");

                    b.Property<string>("HistoryRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InteriorAndEquipmentCondition")
                        .HasColumnType("bit");

                    b.Property<bool>("InteriorAndEquipmentConditionRemarks")
                        .HasColumnType("bit");

                    b.Property<bool>("LeakInsepction")
                        .HasColumnType("bit");

                    b.Property<string>("LeakInsepctionCheck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manfacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ObdScan")
                        .HasColumnType("bit");

                    b.Property<string>("ObdScanRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallCarCondition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PaintInsepction")
                        .HasColumnType("bit");

                    b.Property<string>("PaintInsepctionRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SuspensionCheck")
                        .HasColumnType("bit");

                    b.Property<string>("SuspensionCheckRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TranmissionCheck")
                        .HasColumnType("bit");

                    b.Property<string>("TranmissionCheckRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WheelCondition")
                        .HasColumnType("bit");

                    b.Property<string>("WheelConditionRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfProduction")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("CarDiagnostics");
                });
#pragma warning restore 612, 618
        }
    }
}
